name: globescout_bloc_01
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  player_repository:
    path: player_repository
  user_repository:
    path: user_repository
  team_repository:
    path: team_repository
  equatable: ^1.0.0
  meta: ^1.0.0

flutter:
  uses-material-design: true